### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by esbullington** [fluffynukeit/adaspark#2]
Hey, nice work. Do you have a license in mind for this flake? If I'm going to use this in an open source project (with credit, of course), I'd want to be sure it has a license (I'm wavering between Ada and Rust for a small tool I have in mind).

`nixpkgs` and other Nix projects, as well as most flakes I've seen, use MIT, for example.

Otherwise, I'll just put one together myself, but I know how much of a pain this probably was.

Thanks.

**Comment by fluffynukeit** [comment]
Agreed, MIT license file committed.  FYI I never really used this flake
aside from putting it together, so keep in mind that it hasn't been vetted.

**Comment by esbullington** [comment]
Thanks, understood. After I merged in #1, it works as well as my lengthy previous manual downloads of the Ada environment, and about 2000x quicker, so I'm thrilled. But I'll take a close look before using it for anything important.

And thanks for the license.
